services:
  - type: web
    name: howlson
    env: php
    plan: free
    buildCommand: |
      set -e
      echo "Installing PHP dependencies..."
      composer install --no-dev --optimize-autoloader --no-interaction
      echo "Installing Bun..."
      curl -fsSL https://bun.sh/install | bash
      export PATH="$HOME/.bun/bin:$PATH"
      echo "Installing Node dependencies..."
      bun install
      echo "Building frontend assets..."
      bun run build
      echo "Setting up storage directories..."
      mkdir -p storage/logs
      mkdir -p storage/framework/cache
      mkdir -p storage/framework/sessions
      mkdir -p storage/framework/views
      mkdir -p bootstrap/cache
      echo "Setting up database..."
      mkdir -p /opt/render/project/src/database
      touch /opt/render/project/src/database/database.sqlite
      chmod 664 /opt/render/project/src/database/database.sqlite
      chmod 775 /opt/render/project/src/database
      echo "Setting permissions..."
      chmod -R 775 storage
      chmod -R 775 bootstrap/cache
      echo "Build completed successfully!"
      
      # Display build directory structure for debugging
      echo "=== BUILD DIRECTORY STRUCTURE DEBUG ==="
      echo "Build working directory: $(pwd)"
      echo "Build directory contents:"
      ls -la
      echo "\nDatabase directory after build:"
      ls -la database/ 2>/dev/null || echo "Database directory not found"
      echo "\nFull project structure:"
      find . -maxdepth 2 -type d | sort
      echo "=== END BUILD DIRECTORY STRUCTURE DEBUG ==="
    startCommand: |
      set -e
      echo "Starting application..."
      
      # Display directory structure for debugging
      echo "=== DIRECTORY STRUCTURE DEBUG ==="
      echo "Current working directory: $(pwd)"
      echo "Directory contents:"
      ls -la
      echo "\nProject root structure:"
      find . -maxdepth 3 -type d | head -20
      echo "\nLooking for database directory:"
      find . -name "database" -type d 2>/dev/null || echo "No database directory found"
      echo "\nChecking /opt/render/project/src structure:"
      ls -la /opt/render/project/src/ 2>/dev/null || echo "Path /opt/render/project/src/ not found"
      echo "\nChecking if database file exists at expected location:"
      ls -la /opt/render/project/src/database/ 2>/dev/null || echo "Database directory not found at /opt/render/project/src/database/"
      echo "=== END DIRECTORY STRUCTURE DEBUG ==="
      
      # Check critical environment variables
      echo "Checking environment variables..."
      if [ -z "$APP_KEY" ]; then
        echo "ERROR: APP_KEY is not set!"
        exit 1
      fi
      if [ -z "$PORT" ]; then
        echo "ERROR: PORT is not set!"
        exit 1
      fi
      
      echo "Checking database file..."
      DB_PATH="/opt/render/project/src/database/database.sqlite"
      if [ ! -f "$DB_PATH" ]; then
        echo "Creating database file at $DB_PATH..."
        mkdir -p /opt/render/project/src/database
        touch "$DB_PATH"
         chmod 664 "$DB_PATH"
         chmod 775 /opt/render/project/src/database
      fi
      
      # Verify database creation and permissions
      echo "=== DATABASE VERIFICATION ==="
      echo "Checking database file existence and permissions:"
      if [ -f "$DB_PATH" ]; then
        echo "✅ Database file exists at: $DB_PATH"
        ls -la "$DB_PATH"
        echo "File size: $(stat -c%s "$DB_PATH" 2>/dev/null || echo 'unknown') bytes"
      else
        echo "❌ Database file NOT found at: $DB_PATH"
      fi
      echo "\nDatabase directory permissions:"
      ls -la /opt/render/project/src/database/ 2>/dev/null || echo "Database directory not accessible"
      echo "=== END DATABASE VERIFICATION ==="
      
      echo "Testing database connection..."
      php -r "try { \$pdo = new PDO('sqlite:/opt/render/project/src/database/database.sqlite'); echo 'Database connection OK\n'; } catch(Exception \$e) { echo 'Database error: ' . \$e->getMessage() . '\n'; exit(1); }"
      
      echo "Running migrations..."
      php artisan migrate --force
      
      echo "Optimizing for production..."
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      
      echo "Starting server on port $PORT..."
      php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_NAME
        value: Howlson
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:GENERATE_NEW_KEY_IN_RENDER_DASHBOARD
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://howlson.onrender.com
      - key: LOG_CHANNEL
        value: errorlog
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /opt/render/project/src/database/database.sqlite
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120
      - key: SESSION_ENCRYPT
        value: false
      - key: SESSION_PATH
        value: /
      - key: SESSION_DOMAIN
        value: null
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: BROADCAST_CONNECTION
        value: log
      - key: FILESYSTEM_DISK
        value: local
      - key: MAIL_MAILER
        value: log
      - key: MAIL_HOST
        value: 127.0.0.1
      - key: MAIL_PORT
        value: 2525
      - key: MAIL_USERNAME
        value: null
      - key: MAIL_PASSWORD
        value: null
      - key: MAIL_ENCRYPTION
        value: null
      - key: MAIL_FROM_ADDRESS
        value: hello@example.com
      - key: MAIL_FROM_NAME
        value: Howlson
      - key: BCRYPT_ROUNDS
        value: 12
      - key: PHP_CLI_SERVER_WORKERS
        value: 4