services:
  - type: web
    name: howlson
    env: php
    plan: free
    buildCommand: |
      set -e
      echo "Installing PHP dependencies..."
      composer install --no-dev --optimize-autoloader --no-interaction
      echo "Installing Bun..."
      curl -fsSL https://bun.sh/install | bash
      export PATH="$HOME/.bun/bin:$PATH"
      echo "Installing Node dependencies..."
      bun install
      echo "Building frontend assets..."
      bun run build
      echo "Setting up storage directories..."
      mkdir -p storage/logs
      mkdir -p storage/framework/cache
      mkdir -p storage/framework/sessions
      mkdir -p storage/framework/views
      mkdir -p bootstrap/cache
      echo "Setting up database..."
      mkdir -p database
      touch database/database.sqlite
      chmod 664 database/database.sqlite
      chmod 775 database
      echo "Setting permissions..."
      chmod -R 775 storage
      chmod -R 775 bootstrap/cache
      echo "Build completed successfully!"
      echo "Database directory created at: $(pwd)/database/"
    startCommand: |
      set -e
      echo "Starting application..."
      
      echo "Initializing application with relative paths..."
      echo "Working directory: $(pwd)"
      
      # Check critical environment variables
      echo "Checking environment variables..."
      if [ -z "$APP_KEY" ]; then
        echo "ERROR: APP_KEY is not set!"
        exit 1
      fi
      if [ -z "$PORT" ]; then
        echo "ERROR: PORT is not set!"
        exit 1
      fi
      
      echo "Checking database file..."
      DB_PATH="$(pwd)/database/database.sqlite"
      echo "Auto-detected database path: $DB_PATH"
      if [ ! -f "$DB_PATH" ]; then
        echo "Creating database file at $DB_PATH..."
        mkdir -p "$(pwd)/database"
        touch "$DB_PATH"
        chmod 664 "$DB_PATH"
        chmod 775 "$(pwd)/database"
      fi
      
      echo "Database setup completed at: $DB_PATH"
      ls -la "$DB_PATH" 2>/dev/null || echo "Database file verification failed"
      
      echo "Testing database connection..."
      php -r "try { \$pdo = new PDO('sqlite:' . getcwd() . '/database/database.sqlite'); echo 'Database connection OK\n'; } catch(Exception \$e) { echo 'Database error: ' . \$e->getMessage() . '\n'; exit(1); }"
      
      echo "Running migrations..."
      php artisan migrate --force
      
      echo "Optimizing for production..."
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      
      echo "Starting server on port $PORT..."
      php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_NAME
        value: Howlson
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:GENERATE_NEW_KEY_IN_RENDER_DASHBOARD
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: ${RENDER_EXTERNAL_URL}
      - key: LOG_CHANNEL
        value: errorlog
      - key: LOG_LEVEL
        value: ${LOG_LEVEL:-error}
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: database/database.sqlite
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: ${SESSION_LIFETIME:-120}
      - key: SESSION_ENCRYPT
        value: false
      - key: SESSION_PATH
        value: /
      - key: SESSION_DOMAIN
        value: ${RENDER_EXTERNAL_HOSTNAME}
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: BROADCAST_CONNECTION
        value: log
      - key: FILESYSTEM_DISK
        value: local
      - key: MAIL_MAILER
        value: log
      - key: MAIL_HOST
        value: localhost
      - key: MAIL_PORT
        value: 2525
      - key: MAIL_USERNAME
        value: null
      - key: MAIL_PASSWORD
        value: null
      - key: MAIL_ENCRYPTION
        value: null
      - key: MAIL_FROM_ADDRESS
        value: noreply@${RENDER_SERVICE_NAME}.onrender.com
      - key: MAIL_FROM_NAME
        value: Howlson
      - key: BCRYPT_ROUNDS
        value: ${BCRYPT_ROUNDS:-12}
      - key: PHP_CLI_SERVER_WORKERS
        value: ${PHP_CLI_SERVER_WORKERS:-4}
      - key: APP_TIMEZONE
        value: ${TZ:-UTC}
      - key: DB_FOREIGN_KEYS
        value: true
      - key: CACHE_PREFIX
        value: ${RENDER_SERVICE_NAME}_cache